### ISSUE TITLE
Config shouldn't be a singleton class

### ISSUE THREAD

**Issue by benningm** [choria-io/mcorpc-ruby-support#126]
There should be one Config per Client object instead of having a global configuration object.

It should be possible for an application to create multiple clients with different brokers.

**Comment by ripienaar** [comment]
Agree yeah, in reality though changing this so late in the game (it's been this way for 13 years) is probably not something we can realistically do :(

The go client is more optimised for complex scenarios

**Comment by benningm** [comment]
I have a rails application that is currently talking with classic activemq/mcollective using the mcollective-client gem. For the migration to choria i need to connect to the activemq broker and multiple choria instances.

Are there ruby bindings for the go client code? Is there a plan what clients will be supported in future?

**Comment by ripienaar** [comment]
No ruby bindings for the Go client, we intend to keep both clients going but I dont intend to structurally change the ruby one unfortunately, it's there as a compatibility layer and I think it shold be focussed on short script like things while the go one for more long running stuff.

If its a rails app, perhaps a REST proxy in go might help? Or even 2 x ruby rest proxies each with its own config
