### ISSUE TITLE
Unable to run (some) Bolt tasks which relies on files

### ISSUE THREAD

**Issue by neomilium** [choria-io/mcorpc-ruby-support#142]
According to [bolt documentation](https://puppet.com/docs/bolt/latest/writing_tasks.html#sharing-task-code), a task that use _shared_ files can mention it internally two ways:
 * Using `_installdir` params (e.g. `$PT__installdir` in shell)
 * Using relative path from script dirname

Running bolt task which relies on files mentionned using relative path failed with _choria_/_mco_

Note : In _Bolt_ documentation, `_installdir` param is used in _Ruby_ example, and relative path is used in _Python_ one.

**Comment by ripienaar** [comment]
We implemented the spec as it was at the time but it’s shifted a bit since. For sure some catch up to do. 

Seems to me this might be some easy additions. Do you feel up to doing a PR for these features?
