### ISSUE TITLE
Missing tag for 2.24.1

### ISSUE THREAD

**Issue by smortex** [choria-io/mcorpc-ruby-support#144]
The release has not been tagged or the tag has not been pushed to GitHub :smiley: 

I guess db4982f662b6c9b3539fd9dea2d10e0555522520 should be tagged 2.24.1:

```
git tag 2.24.1 db4982f662b6c9b3539fd9dea2d10e0555522520
git push --tags
```

Thanks!

**Comment by ripienaar** [comment]
pushed it to my own fork and not upstream :) fixed now thank you
