### ISSUE TITLE
MCollective::Util::Choria does not process options as choria does

### ISSUE THREAD

**Issue by smortex** [choria-io/mcorpc-ruby-support#149]
While switching (in a side project) from querying PupetDB with `pl-puppetdb-ruby` to `choria-mcorpc-support`'s `MCollective::Util::Choria` class (to benefit from `choria.conf` support to target a project-defined PuppetDB infrastructure), I realized that `choria` and `mco` are not in sync with processing of the settings.

This seems not to be user-visible anymore since `mco` now rely on `choria` for discovery.  Yet, this API is still packaged and offers more flexibility than the Puppet client-tools configuration (`~/.puppetlabs/client-tools/puppetdb.conf`).

I would like to align the behavior in the gem to [the one implemented in choria](https://github.com/choria-io/go-choria/pull/1109).

**Comment by ripienaar** [comment]
Hm different how? That’s interesting thought I managed to port things 1:1 but I guess there could be weirdness :)

**Comment by ripienaar** [comment]
Fwiw I was thinking of deleting this code :)

**Comment by smortex** [comment]
Not checking the right setting for enabling/disabling SRV lookup and not using the server hardcoded in `choria.conf` if some SRV record returns another value.  My PR is ready :grin: 

Yeah, I was wondering how "safe" it would be to switch away form `pl-puppetdb-ruby` since mco does not use this code anymore :-S.  But the value is sooo huge for me that I can consider extracting it if required.
