### ISSUE TITLE
Custom configuration files aren't passed to choria during discovery

### ISSUE THREAD

**Issue by chrisboulton** [choria-io/mcorpc-ruby-support#164]
We run Choria with a number of unique configuration files, and are attempting to just now move to the most recent releases, which seem to change the discovery to shell out to `choria` vs executing directly from within MCO.

When using a custom configuration file, presently the path to that config file is not passed into Choria, and as such it tries to execute with the default.

Given this:

```
$ mco_choria_prd choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.24.1
         Choria Version: 0.19.0
     Client Config File: /Users/chris/.choriarc
     Active Config File: /Users/chris/.mcollective.choria.d/prd/client.conf
```

I'd expect: `choria discover -j --silent --config /Users/chris/.mcollective.choria.d/prd/client.conf -T mcollective -A rpcutil --dm mc` but instead, the following is executed: `choria discover -j --silent -T mcollective -A rpcutil --dm mc`

**Comment by ripienaar** [comment]
How do you set this configuration file to the mco client? with --config or something?

**Comment by chrisboulton** [comment]
Yup, exactly. We have some convenience wrappers for `mco`: `mco_choria_prd` etc which do `mco -c ~/.mcollective.choria.d/prd/client.conf`

**Comment by ripienaar** [comment]
Hmm ok. Will check in the morning.

**Comment by ripienaar** [comment]
thank you
